apiVersion: v1
kind: ConfigMap
metadata:
  name: api-configmap
  namespace: 2023800251
  labels:
    app: mediconnect-api
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_URL: "jdbc:postgresql://postgres-service:5432/mediconnect"
  SERVER_PORT: "8080"
