apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: 2023800251
  labels:
    app: postgres
type: Opaque
data:
  POSTGRES_DB: bWVkaWNvbm5lY3Q=
  POSTGRES_USER: bWVkaWNvbm5lY3Q=
  POSTGRES_PASSWORD: bWVkaWNvbm5lY3QxMjM=
