apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: "2023800251"
  labels:
    app: postgres
data:
  POSTGRES_DB: "mediconnect"
  POSTGRES_USER: "mediconnect"
  POSTGRES_PASSWORD: "mediconnect123"
